### ISSUE TITLE
Видео

### ISSUE THREAD

**Issue by MrHacker117** [AppleInternal/iOS#1]
Братан, ты серьёзно? Опять выкладываешь вместо туториала, на мемную музыку?!

**Comment by AppleInternal** [comment]
> Братан, ты серьёзно? Опять выкладываешь вместо туториала, на мемную музыку?!

этот репо это весь рофл

**Comment by MrHacker117** [comment]
Пон с тобой. Иди-ка ты лучше скачай JailBreak, и скопируй все системные папки.

**Comment by AppleInternal** [comment]
> Пон с тобой. Иди-ка ты лучше скачай JailBreak, и скопируй все системные папки.

иос больше весит чем может поднять гитхаб (5гб максимум для каждого репо, но есть исключения)

**Comment by MrHacker117** [comment]
Хорошо, а чём проблема запихнуть всё в облачном сервисе terabox

**Comment by AppleInternal** [comment]
> Хорошо, а чём проблема запихнуть всё в облачном сервисе terabox

там такое хранить нельзя хех

**Comment by MrHacker117** [comment]
Хз, но у меня почти получилось

**Comment by MrHacker117** [comment]
Кстати, будешь со мной в разработке?

**Comment by AppleInternal** [comment]
> Кстати, будешь со мной в разработке?
> 
> 

всмысле?..
